name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint (allow warnings)
      run: npm run lint || echo "ESLint completed with warnings"
      
    - name: Check Prettier formatting
      run: npm run format:check
      
    - name: Run tests
      run: npm test
      
    - name: Build Storybook
      run: npm run build-storybook
      
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: storybook-build
        path: storybook-static/

  docker-build:
    needs: code-quality
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t wang_yue_ui_garden_build_checks .
        
    - name: Test Docker container
      run: |
        docker run -d -p 8018:80 --name wang_yue_coding_assignment13 wang_yue_ui_garden_build_checks
        sleep 10
        curl -f http://localhost:8018 || exit 1
        docker stop wang_yue_coding_assignment13
